### ISSUE TITLE
[Security Issue] Secret Detected in Repository

### ISSUE THREAD

**Issue by MrJackQiao** [game-ci/cli#39]
Hi,

We are a team of security researchers from the University of Delaware in the United States. We are reaching out to notify you that one of the files in the repository contains secrets in plain text. It is crucial that the secrets are set up properly to safeguard the integrity and security of your system and its users.

Please reach out to qiaochu@udel.edu for more information.  

Best regards,
UD X-Lab

**Comment by webbertakken** [comment]
Fixed in #40.

To be fair though: CodeCov didn't use to have the "tokenless" option when this was implemented and you had two options:

- Either you paste the token in your workflow so that the diff correctly shows up for all contributors
- Or you use it as a secret, which means that nobody outside the org will get coverage diffs in their PRs, as per the secrets [not being passed](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow) to workflows running on forks

In practice this was a trade-off and we never considered it to be a real security concern.

I'd also kindly ask you to follow security policy or email maintainers directly instead of immediately publicly exposing security related information (i.e. that there is a secret to find in the repo). We might not always be quicker to respond than people with bots that scrape GitHub for the word "security issue". 😄
